#include "./paredes.h"
#include "./piso.h"
#include "./sofa.h"
#include "./almofadas_sofa.h"
#include "./poltrona.h"
#include "./almofadas_poltrona.h"
#include "./mesas.h"
#include "./abajur.h"
#include "./abajur_suporte.h"
#include "./armario.h"
#include "./armario_gavetas.h"
#include "./armario_puxadores.h"

